name: Deploy Databricks Bundle

on:
  push:
    branches:
      - main
    paths:
      - "databricks.yml"
      - "resources/**"
      - "2609_e-commerce_etl/**"
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy bundle
        run: databricks bundle deploy https://adb-7405614601018594.14.azuredatabricks.net/
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

